language: ruby
sudo: false
cache: bundler

rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - 2.5.1
  - ruby-head
  - jruby-9.1.16.0
  - jruby-head
  - truffleruby

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.1.16.0
    - rvm: truffleruby

before_install:
  - gem install bundler

# script: bundle exec rspec spec

notifications:
  irc: "irc.freenode.net#rubber"
